#include <iostream>
#include <array>

using namespace std;

int main(){
	string IN;
	array<string, 4> NAME = {
	"Bighead Carp",
	"Silver Carp",
	"Grass Carp",
	"Black Carp",
	};
	array<string, 4> eDNA = {
	"AACTTAAATAAACAGATTATTCCACTAACAATTGATTCTCAAATTTATTACTGAATTATTAACTAAAATCTAACTCAAGTATATTATTAAAGTAAGAGACCACCTACTTATTTATATTAAGGTATTATATTCATGATAAGATCAAGGACAATAACAGTGGGGGTGGCGCAAAATGAACTATTACTTGCATCTGGTTTGGAATCTCACGGACATGGCTACAAAATTCCACCCCCGTTACATTATAACTGGCATATGGTTAAATGATGTGAGTACATACTCCTCATTAACCCCACATGCCGAGCATTCTTTTAT",
	"CCTGAGAAAAGAGTTGTTCCACTATAATTGGTTCTCAAATATTTCCTTGAAATATTAACTTCTATTTAATTTAACTATATTAATGTAGTAAGAAACCACCTACTGGTTTATATTAAGGTATTCTATTCATGATAAGATCAGGGACAATAATCGTGGGGGTGGCGCAGAATGAACTATTACTTGCATTTGGC",
	"GAGTTTCTGACTTCTACCCCCTTCTTTCCTCCTACTATTAGCCTCTTCTGGTGTTGAGGCCGGAGCTGGAACAGGGTGAACAG",
	"ACACCACGTTCTTTGACCCAGCAGGCGGAGGAGACCCAATCCTATATCAACACCTGTTCTGATTCTTCGGCCACCCAGAAGTTTACATTCTTATTTTACCCGGGTTTGGGATCATTTCAC"
	};
	cout << "INPUT: ";
	cin >> IN;
	for (int i = 0;i <= 3;i++){
		int ans = IN.find(eDNA[i]);
		if (ans != -1){
			cout << "It is ";
			cout << NAME[i] << endl;
		}else{
			cout << "It is not Carp"<< endl;
		}
	}
		
}
